<?php

// config.php
return [
    'basepath' => '/Users/thorchristopher/Documents/git/thortype/public/static/fonts',
    'fonts' => [
        '16-segment-display' => '16-segment-display.otf',
        'anderson' => 'anderson.ttf',
        'belleview' => 'belleview.otf',
        'betong' => 'betong.ttf',
        'borgen' => 'borgen.otf',
        'brush-off' => 'brush-off.ttf',
        'buckley-junior' => 'buckley-junior.otf',
        'cardboard-cutout' => 'cardboard-cutout.otf',
        'caroline' => 'caroline.ttf',
        'college-sans' => 'college-sans.ttf',
        'demodulator' => 'demodulator.ttf',
        'dm80' => 'dm80.otf',
        'giovanni' => 'giovanni.ttf',
        'hairline' => 'hairline.otf',
        'high-society' => 'high-society.ttf',
        'hothead' => 'hothead.ttf',
        'i8080' => 'i8080.ttf',
        'inverted-stencil' => 'inverted-stencil.ttf',
        'klub-katz' => 'klub-katz.otf',
        'manos' => 'manos.ttf',
        'metal-plate' => 'metal-plate.otf',
        'modum' => 'modum.otf',
        'monomod' => 'monomod.otf',
        'ortho-graphix' => 'ortho-graphix.otf',
        'pipeline' => 'pipeline.otf',
        'ragtime' => 'ragtime.otf',
        'roland' => 'roland.ttf',
        'salome' => 'salome.ttf',
        'snufkin' => 'snufkin.otf',
        'solid-sans' => 'solid-sans.ttf',
        'sullivan' => 'sullivan.ttf',
        'taylor-gothic' => 'taylor-gothic.otf',
        'taylor' => 'taylor.otf',
        'tuscan-black' => 'tuscan-black.otf',
        'tuscan-modular' => 'tuscan-modular.otf',
        'zx80' => 'zx80.ttf',
    ],
];

