package com.tcarisland.thortype.fontinspector.gui.components;

import lombok.Data;

import javax.swing.*;
import java.awt.*;

@Data
public class FontInspectorPanel {
    private JPanel fontInspectorPanel;
    private FontTableList tableListPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        fontInspectorPanel = new JPanel();
        fontInspectorPanel.setLayout(new BorderLayout(0, 0));
        tableListPanel = new FontTableList();
        fontInspectorPanel.add(tableListPanel.$$$getRootComponent$$$(), BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return fontInspectorPanel;
    }
}
