package com.tcarisland.thortype.fontinspector.gui.components;

import lombok.Data;
import org.apache.fontbox.ttf.TTFTable;

import javax.swing.*;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeSelectionModel;
import java.awt.*;
import java.util.Collections;
import java.util.Hashtable;
import java.util.Map;


@Data
public class FontTableList {
    private JPanel tableListPanel;
    private JTree tableTree;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        tableListPanel = new JPanel();
        tableListPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(300, 480));
        tableListPanel.add(scrollPane1, BorderLayout.CENTER);
        tableTree = new JTree();
        tableTree.setMinimumSize(new Dimension(0, 0));
        scrollPane1.setViewportView(tableTree);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return tableListPanel;
    }
}
